import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { renderToStaticMarkup } from 'react-dom/server';

const dataModule = (text, replacements = {}) => {
  let output = ts.transpileModule(text, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, jsx: ts.JsxEmit.ReactJSX } }).outputText;
  for (const [from, to] of Object.entries(replacements)) output = output.replaceAll(`from '${from}'`, `from '${to}'`).replaceAll(`from "${from}"`, `from "${to}"`);
  return `data:text/javascript;base64,${Buffer.from(output).toString('base64')}`;
};
const authUrl = dataModule(readFileSync(new URL('../src/auth.ts', import.meta.url), 'utf8').replace(/^const API_BASE =.*$/m, "const API_BASE = 'https://stormhacks.onrender.com';"));
const modelUrl = dataModule(readFileSync(new URL('../src/model.ts', import.meta.url), 'utf8'));
const { deviceApi, devicePacket, AddDevice } = await import(dataModule(readFileSync(new URL('../src/devices.tsx', import.meta.url), 'utf8'), { './auth': authUrl, './model': modelUrl, react: import.meta.resolve('react'), 'react/jsx-runtime': import.meta.resolve('react/jsx-runtime') }));
const calls = []; let reply;
globalThis.fetch = async (url, options) => { calls.push({ url, ...options }); return reply.clone(); };
reply = new Response(JSON.stringify([]));
assert.deepEqual(await deviceApi.list('user-token'), []);
assert.equal(calls.at(-1).headers.Authorization, 'Bearer user-token');
reply = new Response(JSON.stringify({ device_id: 'serial/42', expires_at: '2099-01-01T00:00:00Z' }));
assert.equal((await deviceApi.pairing('user-token', 'code/42')).device_id, 'serial/42');
assert.equal(calls.at(-1).url.endsWith('/pairing/code%2F42'), true);
reply = new Response(null, { status: 204 });
await deviceApi.confirm('user-token', 'code/42');
assert.equal(calls.at(-1).url.endsWith('/pairing/code%2F42/confirm'), true);
assert.equal(calls.at(-1).method, 'POST');
reply = new Response(JSON.stringify({ device_id: 'serial/42', name: 'Bedroom' }));
await deviceApi.update('user-token', 'serial/42', { name: 'Bedroom', min_temperature: 18, target_temperature: 21, max_temperature: 26 });
assert.equal(calls.at(-1).method, 'PATCH');
assert.equal(calls.at(-1).url.endsWith('/devices/serial%2F42'), true);
assert.equal(JSON.parse(calls.at(-1).body).target_temperature, 21);
reply = new Response(null, { status: 204 });
await deviceApi.unpair('user-token', 'serial/42');
assert.equal(calls.at(-1).method, 'DELETE');
const reading = { Centre: 21, Window: 20, Heater: 25, Door: 21, 'Far wall': 21.5, timestamp: '2026-10-04T12:00:00Z' };
assert.equal(devicePacket({}, 'serial/42'), null);
assert.equal(devicePacket({ 'serial/42': reading }, 'serial/42').Centre, 21);
assert.equal(devicePacket({ 'serial/42': { readings: reading, timestamp: reading.timestamp } }, 'serial/42').Window, 20);
assert.throws(() => devicePacket({ 'serial/42': { Centre: 21 } }, 'serial/42'), /Invalid or missing/);
const markup = renderToStaticMarkup(AddDevice({ onDemo() {} }));
assert.match(markup, /Add your first device/);
assert.match(markup, /Explore the demo room/);
assert.equal((markup.match(/<li>/g) || []).length, 3);
console.log('Device checks passed: pairing, authorized management, encoded IDs, missing/invalid readings, and three-step onboarding.');
